### ISSUE TITLE
How to set device to GPU?

### ISSUE THREAD

**Issue by Nikeshbajaj** [srikris/datascience-bowl#2]
By default device is set to CPU how to change it to GPU. on CPU it is taking too much time

**Comment by srikris** [comment]
This should work on a GPU by default if you have one. Are you using a MAC? I believe there is an issue with GPUs and Mac.

**Comment by Nikeshbajaj** [comment]
I am using Ubuntu 14.04 and IPython, I started programm and It took 6 hours for 5 itterations

**Comment by srikris** [comment]
It definitely should not take 6 hours for 5 iterations. It should be around 100x faster.

There are 2 possible issues. 

(a) Did you install the GPU version of GraphLab Create?

(b) Do you have the right drivers for it? Sometimes, you can have the GPU card and not have the right drivers for it. 

Let me know what your thoughts are.
